 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S0xxXepHinh;


import java.awt.Graphics;
import java.awt.GridLayout;
import static java.lang.Thread.sleep;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author sonvu
 */
public class XepHinh extends javax.swing.JFrame {

    static int count = 0;
    static int time = 0;
    static JLabel lblCount = new JLabel("Count: 0");
    static JLabel lblTime = new JLabel("Time: 0");
    int size;
    QLButton ql;

    /**
     * Creates new form XepHinh
     */
    public XepHinh() {
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        ql = new QLButton(3);
        PanelXH.setLayout(new GridLayout(3, 3));
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                PanelXH.add(ql.a[i][j]);
                ql.a[i][j].setEnabled(false);
            }
        }
        PanelCount.setLayout(new GridLayout(2, 1));
        PanelCount.add(lblCount);
        PanelCount.add(lblTime);

    }
    static countTime cTime = new countTime();

    public static class countTime extends Thread {

        @Override
        public void run() {
            super.run();

            while (true) {
                try {
                    sleep(1000);
                    time++;
                    lblTime.setText("Time: " + time);
                } catch (InterruptedException ex) {
                    Logger.getLogger(XepHinh.class.getName()).log(Level.SEVERE, null, ex);
                } 

            }
        }

    }

    static void changeCount() {
        lblCount.setText("Count: " + count);
    }

    void rdm(int size) {
        Random r = new Random();
        for (int i = 0; i < 100000; i++) {
            int n = r.nextInt(size * size);
            ql.tron(n);
        }

    }
    // thua;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelXH = new javax.swing.JPanel();
        CbbSize = new javax.swing.JComboBox();
        PanelCount = new javax.swing.JPanel();
        btnNewGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelXH.setPreferredSize(new java.awt.Dimension(300, 300));
        PanelXH.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PanelXHAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout PanelXHLayout = new javax.swing.GroupLayout(PanelXH);
        PanelXH.setLayout(PanelXHLayout);
        PanelXHLayout.setHorizontalGroup(
            PanelXHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        PanelXHLayout.setVerticalGroup(
            PanelXHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        CbbSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3 x 3", "4 x 4" }));
        CbbSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbSizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCountLayout = new javax.swing.GroupLayout(PanelCount);
        PanelCount.setLayout(PanelCountLayout);
        PanelCountLayout.setHorizontalGroup(
            PanelCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        PanelCountLayout.setVerticalGroup(
            PanelCountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        btnNewGame.setText("New Game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(PanelXH, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewGame))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(CbbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewGame))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(PanelXH, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        size = CbbSize.getSelectedIndex();
        if (cTime.isAlive()) {
            time = -1;
            cTime.resume();
        } else {
            time = -1;
            cTime.start();
        }

        switch (size) {
            case 0:
                create(3);

                break;
            case 1:
                create(4);
                break;
        }


    }//GEN-LAST:event_btnNewGameActionPerformed
    void create(int length) {
        ql = new QLButton(length);
        PanelXH.removeAll();
        PanelXH.setLayout(new GridLayout(length, length));
        for (int i = 0; i < length; i++) {
            for (int j = 0; j < length; j++) {
                PanelXH.add(ql.a[i][j]);
            }
        }
        count = 0;
        lblCount.setText("Count: " + count);
        rdm(length);
    }
    private void PanelXHAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PanelXHAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelXHAncestorAdded

    private void CbbSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbSizeActionPerformed


    }//GEN-LAST:event_CbbSizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XepHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XepHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XepHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XepHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XepHinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbbSize;
    private javax.swing.JPanel PanelCount;
    private javax.swing.JPanel PanelXH;
    private javax.swing.JButton btnNewGame;
    // End of variables declaration//GEN-END:variables
}
